# Tests a broad set of Quarto functionality that users are likely to encounter.
# A failure indicates some signficant portion of functionality is likely to be broken.
name: Test Suite
on:
  push:
    # only trigger on branches, not on tags
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-suite:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    name: Run test suite
    if: github.repository == 'quarto-dev/quarto-markdown'

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Homebrew
        if: runner.os == 'macOS'
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main

      # Rust setup
      - name: Set up Rust nightly (macOS)
        if: runner.os == 'macOS'
        uses: dtolnay/rust-toolchain@nightly

      - name: Set up Rust nightly (using rustup)
        if: runner.os == 'Linux' || runner.os == 'Windows'
        run: rustup override set nightly
        shell: bash

      - name: Output rust version
        run: rustup --version
        shell: bash
        
      # Pandoc setup
      - name: Install pandoc
        uses: pandoc/actions/setup@v1

      # tree-sitter CLI setup
      - uses: tree-sitter/setup-action@v2
        with:
          install-lib: false

      # build and run tests
      - name: Build
        run: cargo build
        shell: bash

      - name: Test inline tree-sitter grammar
        working-directory: crates/tree-sitter-qmd/tree-sitter-markdown-inline
        run: tree-sitter test

      - name: Test block tree-sitter grammar
        working-directory: crates/tree-sitter-qmd/tree-sitter-markdown
        run: tree-sitter test
        
      - name: Test Rust code
        run: cargo test
        shell: bash
