# Tests a broad set of Quarto functionality that users are likely to encounter.
# A failure indicates some signficant portion of functionality is likely to be broken.
name: Test Suite
on:
  push:
    # only trigger on branches, not on tags
    branches:
      - main

jobs:
  test-suite:
    name: Run test suite
    if: github.repository == 'quarto-dev/quarto-markdown'
    runs-on: ubuntu-latest
    steps:
      - name: Temporarily modify the rust toolchain version
        run: rustup override set nightly
        shell: bash

      - name: Output rust version for educational purposes
        run: rustup --version
        shell: bash
        
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: | 
          curl -LO https://github.com/jgm/pandoc/releases/download/3.7.0.2/pandoc-3.7.0.2-1-amd64.deb
          sudo dpkg -i pandoc-3.7.0.2-1-amd64.deb
        shell: bash

      - name: Install tree-sitter CLI
        run: |
          sudo apt-get install libc6-dev
          sudo apt-get install gcc-multilib
          curl -LO https://github.com/tree-sitter/tree-sitter/releases/download/v0.25.8/tree-sitter-linux-x86.gz
          gunzip tree-sitter-linux-x86.gz
          chmod +x tree-sitter-linux-x86

      - name: Build
        run: cargo build
        shell: bash

      - name: Test inline tree-sitter grammar
        run: |
            cd crates/tree-sitter-qmd/tree-sitter-markdown-inline
            ../../../tree-sitter-linux-x86 test

      - name: Test block tree-sitter grammar
        run: |
            cd crates/tree-sitter-qmd/tree-sitter-markdown
            ../../../tree-sitter-linux-x86 test

      - name: Test Rust code
        run: cargo test
        shell: bash

